language: java
before_install:
- chmod +x mvnw
deploy:
  provider: heroku
  api_key:
    secure: ER8JznK8IZO39ajLjkXD0GGVUpSjLdlCapYcTf5U4zA5QSC+h4ikA3JgayNxkg0nouqvytQFMczetmYSH3Z9AfppOnCtej5kJtnKXo2N5qVSGO9eqjsxj1CGkQRTWtFuHOyrELcF1Wrc83+BQjY3HIiRuU2fR5Ar/c7vPpFdg873Z79j1CUtXksq56UBC24ffb3FPD2G0CtMWM36584eQMTmMYBr7RhO+cCssQP9KhXK3nCsLe/hq+qZ5UTj4781DgMQh/OOXuBG7YOTjzrxVqU5L1dL24AXw2m0DbRlHaj9WwPVdGGZdVv3HmJV7v+RCMFC2ltuvLsuE6b7U2iQpD7QrtJVVpgzv4J2dOAGS7QVsE99J79zqg18j3WV6hrmZfabwQ6n52JYctvdfAwZtHkpo/4CnNbQfK3JwYl1gSEODsE/kMtdSEwI9440ROe5rhkOY4VZXebq6MCc58klyQ67K71YMfqIQ7oWYCl4tcgvqUaL++M2AvN6/+P00MALCMfknNQYS4nIzfCIUblkTeanqskekgc/lUUzkEhPP0ku9v+G5+8wild7xVuOTVMAy63pLg5B8YBu3lj50q6svzRV1BUlZdkMRUd/Xcrdp8EuxWtVPgsmTiVh5SNCKrr6RDTw7JnSQssPGDF9baPJEotX1k0tEtT1TCCSjTztgpE=
  dev: paawww-dev
  staging: paawww-staging
  master: paawww-production
  setup/project: paawww-dev
