language: java
before_install:
- chmod +x mvnw
deploy:
  api_key:
    secure: Q05+2PjdPFpm3VNM078Bi4mC8CYj+VCYXzAdEODknXs0lvhseMc125zMQIqxPzlJrQ88utmtba+IYk843oydChv7+ZI90FL5INioIxwzcWrQ72/q79CXl6DOdEpUplGF0tAXIsySHDF6t7MjG22M0zzTer4DQFLe3guo62W1GSowiTkAaCXjewGz3DU1Jhr7ChdpT4aErXFjRPuI6uv07SbJ3C4Agzu4epSQkinx1NgEgpsKGE8DM3QJ5jB9176Y1stmg/G133OehfiaNrUhFGZDYwcXK+F0kkv+34w3PyP+PcgsxvLxcCSNH7n2uhXXxd77F+wM9KMi2j7oVq8C3i6lJ4A0Vur/f48ZWft14DX1Z9hs8uiepNTDisPg2f+HhbEz5ZCdVrX9baGXPqHBK9TjujZ1FnX4cOsNlhOE89dU/DdXBeshM/Y61fEfiB++5vdzOePo5PVq3/EWmVgVc6zVJbuNOFJZeKax6+49DgIbAFe0yAvEBPCAQD97nvhOuP5BAECfGQx5NpbIFnpanjLwt2tW7k4BseJXnp766ZfF540i0UcliOHVFfvO6Bhxzb7vso9e4uutSdDGBlUy+9NMJ5SINQSHrPbBJTjOnIDnr+iiw4CRsK+obRjqHxie6ZAlCGevYDO/66axN7PglgdFnirmcHuEjDoQbjR4i0o=
